### ISSUE TITLE
Upgrade SNS Webhook for AWS PHD

### ISSUE THREAD

**Issue by jihyungSong** [spaceone-dev/plugin-aws-sns-mon-webhook#39]

**Comment by jihyungSong** [comment]
Currently, 
AWS SNS Webhooks plugin are developed based on Cloudwatch data. Futher implementation is required that converts it into alert data of the Monitoring service when PHD based notification data are came in.

PHD sample data is available at AWS Eventbridge.

Attaching some sample data.

`{
  "version": "0",
  "id": "7bf73129-1428-4cd3-a780-95db273d1602",
  "detail-type": "AWS Health Event",
  "source": "aws.health",
  "account": "123456789012",
  "time": "2016-06-05T06:27:57Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "eventArn": "arn:aws:health:ap-southeast-2::event/AWS_ELASTICLOADBALANCING_API_ISSUE_90353408594353980",
    "service": "ELASTICLOADBALANCING",
    "eventTypeCode": "AWS_ELASTICLOADBALANCING_API_ISSUE",
    "eventTypeCategory": "issue",
    "startTime": "Sat, 04 Jun 2016 05:01:10 GMT",
    "endTime": "Sat, 04 Jun 2016 05:30:57 GMT",
    "eventDescription": [{
      "language": "en_US",
      "latestDescription": "A description of the event will be provided here"
    }]
  }
}`

`{
  "version": "0",
  "id": "7bf73129-1428-4cd3-a780-95db273d1602",
  "detail-type": "AWS Health Event",
  "source": "aws.health",
  "account": "123456789012",
  "time": "2016-06-05T06:27:57Z",
  "region": "us-west-2",
  "resources": ["i-abcd1111"],
  "detail": {
    "eventArn": "arn:aws:health:us-west-2::event/AWS_EC2_INSTANCE_STORE_DRIVE_PERFORMANCE_DEGRADED_90353408594353980",
    "service": "EC2",
    "eventTypeCode": "AWS_EC2_INSTANCE_STORE_DRIVE_PERFORMANCE_DEGRADED",
    "eventTypeCategory": "issue",
    "startTime": "Sat, 05 Jun 2016 15:10:09 GMT",
    "eventDescription": [{
      "language": "en_US",
      "latestDescription": "A description of the event will be provided here"
    }],
    "affectedEntities": [{
      "entityValue": "i-abcd1111",
      "tags": {
        "stage": "prod",
        "app": "my-app"
      }
    }]
  }
}`

**Comment by jihyungSong** [comment]
PHD data coming through SNS is mapped to Monitoring Alert data as shown below.

- event_key: eventArn
- event_type: ALERT (No RECOVERY)
- severity: Issue, ScheduledChange -> ERROR | accountNotification -> INFO
- resource.resource_id: eventArn
- resource.resource_type: aws.health
- description: eventDescription.latestDescription
- title: eventTypeCode (Need to change string format, ex. AWS_ELASTICLOADBALANCING_API_Issue => Aws Elasticloadbalancing Api Issue)
- rule: eventTypeCategory
- occured_at: startTime (Need to change date format)
- additional_info: id, account, affected_resources, region, service, eventTypeCode

**Comment by jihyungSong** [comment]
Update mapping data

- description : {{ eventDescription.latestDescription (account) }}

Add account information in description string.
Temporarily, the description information will be used for the project routing condition pattern.

**Comment by stat-kwon** [comment]
This is a list of questions before development.

**Q1. I wonder if it is not necessary to put in additional_info for variables that are not used in the suggested spec.**

→ (Song) 
First of all, it seems that it is enough to bring only the values presented above. If you think you will need more information in the future, please add it at that time.

**Q2. We can have both English and Korean in  "description: event Description.latest Description". 
I wonder if it is possible to develop to print both.**

→ (Song)
Yes. Do not distinguish between Korean and English, just receive and deliver as soon as it arrives.

**Q3. I wonder if the following suggested spec can be configured as in the example below when adding description.**

Update mapping data
- description : {{ eventDescription.latestDescription (account) }}
Add account information in description string.
Temporarily, the description information will be used for the project routing condition pattern.

```python 
description = "Account : 12345678 This is an example description to help you understand." 
```
-> (Song) 
Decsrption information written as an example.
```python
desciprion : "This is an example description to help you understand. (Account: 12345)"
```

**Q4. From the user's point of view, resources seem to be important.
If the above suggested spec is followed, additional_info is relatively
It appears to be included in the supplementary information.**

→ (Song) 
Currently, there is no place to put affected resource information in our Alert information, 
so we put it in additional_info. Since the message sent to the end user will contain the information, 
it doesn't seem to matter if I put it in additional_info.

**Comment by stat-kwon** [comment]
Below is the result after completing the development.
As you can see, **all the suggested specs have been reflected.**

An additional consideration is the structural part. I will write later.

```python
# Result of processing data received from cloudwatch
{'results': [{'additional_info': {'AWSAccountId': '123456789012',
                                  'AlarmArn': 'arn:aws:cloudwatch:ap-northeast-2:257706363616:alarm:ContainerInsight-pod_cpu_utilization',
                                  'AlarmName': 'ContainerInsight-pod_cpu_utilization',
                                  'OldStateValue': 'ALARM',
                                  'Region': 'Asia Pacific (Seoul)'},
              'description': 'Thresholds Crossed: 1 out of the last 1 '
                             'datapoints [0.46522264287069004 (27/06/21 '
                             '13:52:00)] was not less than the lower '
                             'thresholds [0.4129373661576242] or not greater '
                             'than the upper thresholds [0.4700330400585261] '
                             '(minimum 1 datapoint for ALARM -> OK '
                             'transition).',
              'event_key': '2a7ac6e9ea3c584f43c2698359fe4df6',
              'event_type': 'RECOVERY',
              'occurred_at': '2021-06-27T13:53:39.351Z',
              'resource': {'name': '[ContainerInsights] '
                                   'ClusterName=cloudone-dev-v1-eks-cluster '
                                   '(Asia Pacific (Seoul))',
                           'resource_id': 'cloudone-dev-v1-eks-cluster',
                           'resource_type': 'ContainerInsights'},
              'severity': 'INFO',
              'title': '"ContainerInsight-pod_cpu_utilization" in Asia Pacific '
                       '(Seoul)'}]}

# Result of processing data received from PHD
{'results': [{'additional_info': {'account': '123456789012',
                                  'affectedEntities': [{'entityValue': 'arn:aws:cloudfront::123456789012:distribution/DSF867DUMMY87SDF',
                                                        'tags': {'app': '',
                                                                 'stage': ''}},
                                                       {'entityValue': 'arn:aws:ec2:us-east-1:123456789012:instance/i-abcd2222',
                                                        'tags': {'app': '',
                                                                 'stage': ''}}],
                                  'eventTypeCode': 'AWS_ABUSE_COPYRIGHT_DMCA_REPORT',
                                  'id': '7bf73129-1428-4cd3-a780-95db273d1602',
                                  'region': 'global',
                                  'service': 'ABUSE'},
              'description': 'A description of the event will be provided here '
                             '(Account:123456789012)',
              'event_key': 'arn:aws:health:global::event/AWS_ABUSE_COPYRIGHT_DMCA_REPORT_2345235545_5323_2018_08_02_02_12_98',
              'event_type': 'ALERT',
              'occurred_at': '2018-08-02T05:30:00.000Z',
              'resource': {'resource_type': 'aws.health'},
              'rule': 'issue',
              'severity': 'ERROR',
              'title': 'Aws Abuse Copyright Dmca Report'}]}
```

**Comment by stat-kwon** [comment]
Currently, the affected resource information is in additional_info, so it is a little difficult to process.
Considering the many uses of affected resources in various areas, the first modification is necessary.

---
### First modification
- AffectedEntities in additional_info need to be converted to string of list.
  EX) For string values, extract only entityValue and save as list 
  ['arn:aws:ec2:us-east 1:12345678:instance/i-abcd1111', 'arn:aws:ec2:us-east-1:12345678:instance/i -abcd1111' ]

### To be changed later
- All affectedEntities are moved to the resource items.
- The current resource is a dictionary type, so multiprocessing is not possible, so change it to a dictionary of list.
- When resource is type-converted, monitoring service and various notification related plugins 
   need to be changed as well (Email, SMS, VoiceCall, Slack, Telegram , etc)
- Those changes need to be done in parallel with the front-side work, so work on it in the next sprint.

---

Accordingly, I will proceed with the first modification.

**Comment by jihyungSong** [comment]
When delivering a PHD message from EventBridge to SNS, if the "Raw Message Delivery" option is enabled, the message cannot be processed because it is not the JSON format. 

Regardless of the Raw Message Delivery option, additional logic is required to process the message.

**Comment by stat-kwon** [comment]
In doing the above, I found the following problems.
![스크린샷 2022-03-16 오후 11 48 59](https://user-images.githubusercontent.com/83386688/158618385-3f0825c4-6726-48b9-a929-d91a63cb60b6.png)

In the case of "phd-info-dev", it was created in the previous development and there was no problem with status.
However, in order to apply Raw Message Delivery option, the status of the newly created "sns-pht-test-temp" is problematic with Pending confirmation.

Accordingly, I will apply the Raw Message Delivery option after solving the pending confirmation issue.

**Comment by stat-kwon** [comment]
We decided to show affectedEntities in the discription through our meeting. 
The development has been completed in the format below.
There are a total of 4 output results of discription. I wonder if all expressions should be unified like in the test sample2.

```
# Test Sample1
'A description of the event will be provided here (Account:123456789012)

Affected Entities: None'

# Test Sample2
'A description of the event will be provided here (Account:123456789012)

Affected Entities:
 - i-abcd1111'

# Test Sample3
'A description of the event will be provided here (Account:123456789012)

Affected Entities:
 - arn:aws:ec2:us-east-1:123456789012:instance/i-abcd1111
 - arn:aws:ec2:us-east-1:123456789012:instance/i-abcd2222'

# Test sample4
'A description of the event will be provided here (Account:123456789012)

Affected Entities:
 - arn:aws:cloudfront::123456789012:distribution/DSF867DUMMY87SDF
 - arn:aws:ec2:us-east-1:123456789012:instance/i-abcd2222'

```

**Comment by jihyungSong** [comment]
LGTM

**Comment by stat-kwon** [comment]
Based on the actual data from AWS Health, we can do exactly the development that applies 
the "Raw Message Delivery" option. A pipeline that can receive PHD has been built.
After actual data is generated from AWS Health, both Enabled and Disabled options will be developed to be compatible.
